import type { BridgeContext, LLMTarget } from "@/types/bridge-context";

export interface TargetConfig {
  targetId: LLMTarget["id"];
  format: string;
  content: string;
}

function buildCursorRules(context: BridgeContext): string {
  return `# AI Bridge Sync — Cursor Rules
# Generated: ${new Date().toISOString()}
# Version: ${context.version}

${context.globalContext}
`;
}

function buildClaudeKB(context: BridgeContext): string {
  return JSON.stringify(
    {
      type: "knowledge-base",
      version: context.version,
      generatedAt: new Date().toISOString(),
      content: context.globalContext,
    },
    null,
    2
  );
}

function buildChatGPTInstructions(context: BridgeContext): string {
  const trimmed =
    context.globalContext.length > 1400
      ? context.globalContext.slice(0, 1397) + "..."
      : context.globalContext;
  return trimmed;
}

function buildGeminiPrompt(context: BridgeContext): string {
  return `[System Context — AI Bridge Sync v${context.version}]
${context.globalContext}`;
}

/** Context file SuperbulletAI reads from the open Roblox project folder */
function buildSuperbulletContext(context: BridgeContext): string {
  return `# Palm Springs Paradise — SuperbulletAI project context
# Generated by AI Bridge Sync v${context.version} at ${new Date().toISOString()}
# Pipeline: VS Code/Cursor → SuperbulletAI → Rojo serve → Roblox Studio

## Locked rules
- Follow .cursor/rules/roblox-mcm.md (single-story MCM, bright blue sky, <5k parts)
- Server-authoritative economy; never trust client currency
- Production Luau lives in src/; merge from staging/ only after Karl/Eddie approval (10-80-10)

## Rojo
- Use \`rojo serve\` (not build) as the primary Studio sync loop
- default.project.json maps src/ → DataModel

## Supabase (cold path)
- Roblox uses SupabaseClient.lua with Secrets: SUPABASE_URL, SUPABASE_ANON_KEY
- Play Solo without secrets = mock mode (no external HTTP)

## Global context (from bridge)
${context.globalContext}
`;
}

const BUILDERS: Record<LLMTarget["id"], (ctx: BridgeContext) => string> = {
  cursor: buildCursorRules,
  claude: buildClaudeKB,
  chatgpt: buildChatGPTInstructions,
  gemini: buildGeminiPrompt,
  superbullet: buildSuperbulletContext,
};

export function buildSuperbulletExport(
  context: BridgeContext
): { path: string; content: string }[] {
  const main = buildSuperbulletContext(context);
  return [
    { path: ".superbullet/project-context.md", content: main },
    {
      path: ".superbullet/pipeline.json",
      content: JSON.stringify(
        {
          version: context.version,
          lastSynced: context.lastSynced,
          line: ["vscode", "superbulletai", "rojo", "roblox-studio"],
          rojoCommand: "rojo serve",
          supabaseSecrets: ["SUPABASE_URL", "SUPABASE_ANON_KEY"],
        },
        null,
        2
      ),
    },
  ];
}

export function generateTargetConfigs(
  context: BridgeContext
): TargetConfig[] {
  return context.targets
    .filter((t) => t.enabled)
    .map((target) => ({
      targetId: target.id,
      format: target.format,
      content: BUILDERS[target.id](context),
    }));
}
